<a href="https://colab.research.google.com/github/favouroo/Python-Basics-Data-Science/blob/Python-for-Data-Science/Week%207.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 7**
Arrays and lists share very similar attributes. From using square brackets, to immutability. Just like Lists, you can access items or elements in an array by accessing the index number.

In Python, your "first number" is "0" except otherwise stated.
What this means is that when counting, from the front, you have 0,1,2...

**E.g.**:
Name = ["Love", "Joy", "Peace"].

To access the item called JOY, you access it this way
Name [1] and not Name [2].
Another way to index is from behind, using [-1] for the last item.

Revisit the notebook on **list** as well as the **python documentation**.

Always remember to **import numpy** on any new notebook. If you're using a notebook you closed, do well to click the "**Run all**" button in the horizontal tab above.

This **notebook** highlights the following concepte:
- Array indexing
- Reshaping arrays
- Concatenating and splitting arrays
- Filtering Arrays
- Sorting Arrays
- Universal Functions
- Statistical measures can be found in NumPy

---
The next notebook will have you introduced to the world of pandas and its libraries.

In [ ]:
import numpy as np

#### **Array indexing**

In [ ]:
x = np.array([1,3,5,7,9])
x
print(f"The first element in the array is {x[0]}.") #first element in the array
print(f"The last element in the array is {x[-1]}.") #last element in the array
print(f"The second to fourth element is {x[1:4]}") #to access the second to fourth elements
print(f"The element between the second and fourth after 2 step is {x[1:4:2]}")

The first element in the array is 1.
The last element in the array is 9.
The second to fourth element is [3 5 7]
The element between the second and fourth after 2 step is [3 7]


In [ ]:
#for 2 dimensional arrays
y = np.array([[1,3,5,7,9], [2,4,6,8,10], [3,6,9,12,15]])
print(f" The two dimensional array is: \n {y}")

 The two dimensional array is: 
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]


In [ ]:
print(y[0,1]) #row 1, column 2 mathematically
print(y[1,3]) #row 2, column 4 mathematically
print(y[2,4]) #row 3, column 5 mathematically

3
8
15


In [ ]:
print(y[0,1:4]) #row 1, column 2, uptill item before index number 4 mathematically

In [ ]:
print(f"For this, we have \n{y[:, 0:3]}") #all the rows, but column 1 to 3 mathematically

In [ ]:
print(y[0:, 2:]) #everything from row 0 to 2, and also column 2 to the end. That is, where row 1 column 3 starts, and row 3 column 5 ends mathematically

[[ 5  7  9]
 [ 6  8 10]
 [ 9 12 15]]


In [ ]:
print(y[0:, 2:4]) #here row 1 and column 3 but also ends with row 3, column 4

[[ 5  7]
 [ 6  8]
 [ 9 12]]


In [ ]:
print(y[1:, 2:4]) #to get 6,8,9,12
print()

print(y[:, 0:3]) #all rows, first to third column
print()

print(y[1:, :])

[[ 6  8]
 [ 9 12]]

[[1 3 5]
 [2 4 6]
 [3 6 9]]

[[ 2  4  6  8 10]
 [ 3  6  9 12 15]]


#### **Reshaping arrays**

You can only reshape to the size of your initial array. For example, you can't reshape an array with a size of 10 to a size of 8.

To do this, call the reshape method and pass the (row, column argurment)

In [ ]:
z = np.arange(4)
print(f"{z} \n")

new_z = z.reshape(2,2)
print(f"The  array of new_z is: \n {new_z}")
print()

#to reshape a 2D to another 2D
arr = np.array([[1,2,3],[4,5,6]])
print(f"The original 2d array is: \n {arr}")
print(f"The shape of this array is {arr.shape} \n\n")


new_arr = arr.reshape(3,2)
print(f"The reshaped 2d array is: \n {new_arr}")
print(new_arr)
print(f"The shape of this array is {new_arr.shape} \n")

[0 1 2 3] 

The  array of new_z is: 
 [[0 1]
 [2 3]]

The original 2d array is: 
 [[1 2 3]
 [4 5 6]]
The shape of this array is (2, 3) 


The reshaped 2d array is: 
 [[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
The shape of this array is (3, 2) 



#### **Concatenation & splitting arrays**

Row wise concatenation must have the same number of columns so that they will be stacked on each other.

To split an array, know the index where the splitting should occur.

In [ ]:
#to concatenate arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b)) #pass into a list but mine worked in a tuple
print(c)

[1 2 3 4 5 6]


In [ ]:
y

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [ ]:
y_y = np.concatenate((y,y)) #row_wise
print(y_y)
print()
#to stack as new columns, you'll pass in an arguement
yy_y = np.concatenate((y,y), axis=1) #column_wise
print(yy_y)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]

[[ 1  3  5  7  9  1  3  5  7  9]
 [ 2  4  6  8 10  2  4  6  8 10]
 [ 3  6  9 12 15  3  6  9 12 15]]


In [ ]:
#another way is to use H stack and V stack method
#using H-stack
y_hstack = np.hstack((y,y))
print(y_hstack)
print()
#using V-stack
y_vstack = np.vstack((y,y))
print(y_vstack)

[[ 1  3  5  7  9  1  3  5  7  9]
 [ 2  4  6  8 10  2  4  6  8 10]
 [ 3  6  9 12 15  3  6  9 12 15]]

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]


In [ ]:
#to split an array
g = np.arange(15, 30)
print(g)
print()

h,i,j = np.split(g, [5,10]) #i starts from index 5, j starts from index 10 for 3 arrays
k,l = np.split(g, [10]) #i starts from index 5, j starts from index 10 for 2 arrays
print(h)
print(i)
print(j)
print(k)
print(l)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]

[15 16 17 18 19]
[20 21 22 23 24]
[25 26 27 28 29]
[15 16 17 18 19 20 21 22 23 24]
[25 26 27 28 29]


In [ ]:
#you cam copy an array using the copy method
x
print(x)
copy_x = x.copy()
print(copy_x)

[1 3 5 7 9]
[1 3 5 7 9]


#### **Filtering Arrays**

In [ ]:
sample = np.array([1,2,3,4,5,6,7,8,9])
print(sample)
sample == 3 #this gives an array of boolean values and will be true only when value is true

[1 2 3 4 5 6 7 8 9]


array([False, False,  True, False, False, False, False, False, False])

In [ ]:
#to use array of boolean values to index the array
#to filter the array to values greater than 5
sample >5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
sample[sample>5] #filtering array of values greater than 5 but not boolean

array([6, 7, 8, 9])

In [ ]:
#to filter array of values that are even
sample[sample % 2==0]

array([2, 4, 6, 8])

In [ ]:
#for 2d arrays
y

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [ ]:
#to filter the array to just odd numbers
y[y%2==1]

array([ 1,  3,  5,  7,  9,  3,  9, 15])

In [ ]:
y>5

array([[False, False, False,  True,  True],
       [False, False,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [ ]:
y[y>5]

array([ 7,  9,  6,  8, 10,  6,  9, 12, 15])

To count the number of elements in an array based on a condition, it count the number of elements greater than 5 then sums the conditions in 0s and 1s

In [ ]:
np.sum(y>5)

np.int64(9)

In [ ]:
#to add the values in an element
np.sum(y[y>5])

np.int64(82)

#### **Sorting Arrays**

In [ ]:
fav = np.array([6,8,33,45,31,2,9,14,6])
fav

array([ 6,  8, 33, 45, 31,  2,  9, 14,  6])

In [ ]:
np.sort(fav) #ascending order

array([ 2,  6,  6,  8,  9, 14, 31, 33, 45])

In [ ]:
np.sort(fav)[::-1] #descending order: steps of -1, but in descending order

array([45, 33, 31, 14,  9,  8,  6,  6,  2])

#### **Universal Functions**
Here, you don't have to loop over a list. They are also known as ***Ufuncs***.

In [ ]:
sample #the same variable under filtering arrays

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sample+3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
sample*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
sample**3

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
np.add(sample, 5) #adds only a particular value to the array

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.power(sample, 3)

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
np.sin(sample)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.cos(sample)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [ ]:
np.exp(sample)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [ ]:
np.sum(sample)

np.int64(45)

#### **Statistical measures can be found in NumPy**

Mean, median, mode, maximum, minimum

In [ ]:
height = np.random.randint(130, 150, (30)) #this means (start, stop, (number of random items in the array))
height

array([135, 132, 149, 139, 134, 132, 132, 143, 130, 137, 148, 130, 148,
       146, 130, 139, 148, 145, 142, 138, 136, 136, 143, 146, 138, 147,
       141, 142, 136, 130])

In [ ]:
np.mean(height)

np.float64(139.06666666666666)

In [ ]:
np.median(height)

np.float64(138.5)

In [ ]:
np.std(height)

np.float64(6.1640535003806995)

In [ ]:
np.min(height)

np.int64(130)

In [ ]:
np.max(height)

np.int64(149)