<a href="https://colab.research.google.com/github/favouroo/Python-Basics-Data-Science/blob/Python-for-Data-Science/Week%206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 6**

In this week, commit to learning about the different modules we have. The [python documentation](https://docs.python.org/3/) should be your friend.


In this week's notebook, I share the following concepts:
- Python modules and importing a module into your python notebook.
- Types of modules we have (e.g math module, dateTime module, random module)
- Following that, I introduce the concept of LIBRARIES – a crucial and unavoidable aspect of Data Science using Python.
- The NumPy library and importing the Numpy library
- Arrays and types of arrays.
- Difference between 1 dimension arrays, 2 dimension arrays
- Array functions and shaoes of arrays.


The next notebook will explain array indexing and other important information there has to be under numpy. Thereafter, we go to pandas library.
As usual, **YT** is your friend.  😊

**NB:** To import a library or a module, you use the **import** keyword.

**Math Module**

In [1]:
import math
print(math.sqrt(25)) #calling the squareroot function

print(math.ceil(9.67)) #calling the function in the math module that returns the smallest integer >= given number

print(math.floor(9.67)) #calling the function in the math module that returns the smallest integer <= given number

print(math.pi) #returns the pi function in mathematics
print(math.e) #returns the pi function in mathematics
print(math.log(2)) #Calculates the natural logarithimic value of 2 (Ln 2 in Mathematics)

5.0
10
9
3.141592653589793
2.718281828459045
0.6931471805599453


**Random module**

In [2]:
import random
print(random.random()) #random value between 0.0 to 1.0, except 1
print(random.randint(1,25)) #random integer between 1-25, except 25
print(random.uniform(12, 67)) #random float between 12 and 67, except 67

numbers = [2,5,6,3,4,8,9,1]
print(random.choice(numbers)) #selects only numbers in the given list

0.4697376052111456
3
37.96706188029547
9


**DateTime module**

In [3]:
import datetime
print(datetime.datetime.now()) #depends on laptop's local time
print(datetime.date.today()) #print's today's date
print(datetime.date.today()-datetime.timedelta(days=3))
print(f"The deadline for the school fees payment of Emeka's 200L school fees is {datetime.date.today()+datetime.timedelta(days=3)}.")

2026-02-13 11:27:51.753912
2026-02-13
2026-02-10
The deadline for the school fees payment of Emeka's 200L school fees is 2026-02-16.


## **Data Libraries**

**NumPy**

Stands for Numerical Python. Used mostly for numerical calculations. Supports large multidimensional arrays anad matrices.

In [4]:
import numpy as np

**Arrays**

Unlike lists, they can only take one data type.

In [5]:
first_array = np.array([2,4,6,8,0])
print(first_array)
type(first_array)

[2 4 6 8 0]


numpy.ndarray

**Creating an array from a tuple**

In [6]:
another_array = np.array((20,40,60,80,100))
print(another_array)
type(another_array)

[ 20  40  60  80 100]


numpy.ndarray

**NumPy datatypes**

In [7]:
varying = np.array([1,3,5,7,9.2])
print(varying)

#dtype is the attribute used to fetch the datatype of an array
print(varying.dtype)

#to specify your dtype as an arguement
var = np.array([2, 4, 6, 8], dtype = np.float32)
print(var)
print(var.dtype)

[1.  3.  5.  7.  9.2]
float64
[2. 4. 6. 8.]
float32


In [8]:
#to change a datatype, use astype method
new_array = first_array.astype(float)
print(new_array)
new_array.dtype

[2. 4. 6. 8. 0.]


dtype('float64')

In [9]:
new_var = (varying.astype(int))
print(new_var)
new_var.dtype

[1 3 5 7 9]


dtype('int64')

**Special Arrays**

**Zeros function**

Used to create an array of zeros

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**Ones function**

An array of 1s

In [11]:
np.ones((3,3)) #(rows, columns)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**To create an array filled with a specific value**

In [3]:
print(np.full(5,9.8)) #creates a 1 dimentsional array. 1 row, 1 column
print(np.full(10,45))

[9.8 9.8 9.8 9.8 9.8]
[45 45 45 45 45 45 45 45 45 45]


**To create an identity matrix**

In [13]:
print(np.eye(4)) #4by4 identity matrix
print(np.eye(3)) #3by3 identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Arange Function**

This function in the NumPy array is used to create a linear sequence

In [14]:
print(np.arange(1,10,2)) #this refers to start at 1, stop at 10, with a step of 2 but exclude 10

[1 3 5 7 9]


**Evenly spaced array**

In [15]:
print(np.linspace(0,10,5)) #this is an exception where the number 10 shows
print(np.linspace(0,10,7))

[ 0.   2.5  5.   7.5 10. ]
[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


**NumPy also has its own random module.**

In [16]:
print(np.random.random((4,3))) # random numbers between 0 and 1, and to fill 4 rows, 3 columns
print()
print(np.random.randint(10, 20, (3,3))) #(3,3) is your shape. It must always be inside a tuple

[[0.00159923 0.87195524 0.90220946]
 [0.39816937 0.31522467 0.3523647 ]
 [0.96028568 0.60023627 0.94153911]
 [0.52768942 0.7987898  0.3721799 ]]

[[12 12 12]
 [15 12 11]
 [13 13 17]]


**Array Dimensions**

In [17]:
array_1d = np.array([1,3,5,7,9])
print(array_1d)

print(array_1d.ndim)

[1 3 5 7 9]
1


In [18]:
array_2d = np.array([[1,3,5],[2,4,6], [3,6,9]]) #2 dimensional arrays.
print(array_2d)

print(array_2d.ndim)

[[1 3 5]
 [2 4 6]
 [3 6 9]]
2


In [4]:
#one-dimensional array
a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print()
#two-dimensional array: #rows and columns
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(f"This is a {b.ndim} dimensional matrix.")
print()
c=np.array([[4,5,6]])
print(c)
print(f"This is a {c.ndim} dimensional matrix.")
print()
#three-dimensional array: depth, rows and columns
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"The three-dimensional matrix is: \n {d}")
print(f"This is a {d.ndim} dimensional matrix")

[1 2 3 4 5]
1

[[1 2 3]
 [4 5 6]]
This is a 2 dimensional matrix.

[[4 5 6]]
This is a 2 dimensional matrix.

The three-dimensional matrix is: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
This is a 3 dimensional matrix


###Shape of arrays
This gives you the number of rows and columns. That is the shape.
3D arrays are mosstly used for images, image processing, etc.

Shapes are always stored in a **TUPLE** and if your **TUPLE** is having just one element, put a comma in front.

##Recall: Attributes of arrays


*   d-type: to check the data type
* ndim: is for checking the dimension
*   shape: for checking shape of array
* size: counts the total number of elements in the array

In [5]:
#to check the shape of your array
print(f"The shape of your array is {a.shape}.")
print(f"The shape of your array is {b.shape}.")
print(f"The shape of your array is {c.shape}.")
print(f"The shape of your array is {d.shape}.")
print()

#to check the size of your array
print(f"The size of your array is {a.size}.")
print(f"The size of your array is {b.size}.")
print(f"The size of your array is {c.size}.")
print(f"The size of your array is {d.size}.")

The shape of your array is (5,).
The shape of your array is (2, 3).
The shape of your array is (1, 3).
The shape of your array is (2, 2, 3).

The size of your array is 5.
The size of your array is 6.
The size of your array is 3.
The size of your array is 12.
